version: "3"
services:
  nginx:
    image: nginx:alpine-3.17
    restart: always
    volumes:
      - ./data/:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx/
    ports:
      - "8080:80"
    networks:
      - progtest

  php:
    image: php:fpm-alpine
    restart: always
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - progtest

  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    expose:
      - 3306
      - 33060
    networks:
      - progtest

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - progtest

networks:
  progtest:

volumes:
  db_data: